- ros_topic_name: "/anafi/image"
  gz_topic_name: "/world/surveillance_building/model/anafi4k/link/base_link/sensor/anafi_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/anafi/camera_info"
  gz_topic_name: "/world/surveillance_building/model/anafi4k/link/base_link/sensor/anafi_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/gz/pose_info"
  gz_topic_name: "/world/surveillance_building/pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/anafi/cmd_vel"
  gz_topic_name: "/world/surveillance_building/model/anafi4k/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ